import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Link from "next/link";
import { Entry, getEntries } from "../graphql/getEntries";

interface EntriesProps {
  entries: Entry[];
}

const Home: NextPage<EntriesProps> = ({ entries }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={`${styles.title} text-3xl font-bold underline`}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ul>
          {entries.map((entry) => (
            <li key={entry.slug}>
              <Link as={entry.uri} href={entry.uri}>
                <a>
                  <h2 style={{ textTransform: "capitalize" }}>{entry.title}</h2>
                  {/* <img src={pokemon.image} alt={`${pokemon.name} picture`} /> */}
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const entries = await getEntries();
  return {
    props: {
      entries: entries ?? null,
    },
  };
};

export default Home;
